/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.macpod.srv1console;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int bottom_bar=0x7f050007;
        public static final int connect_button=0x7f050002;
        public static final int laser_off_button=0x7f050009;
        public static final int laser_on_button=0x7f050008;
        public static final int left_bar=0x7f050004;
        public static final int revert_button=0x7f05000f;
        public static final int right_bar=0x7f050005;
        public static final int s1_1_button=0x7f05000a;
        public static final int s1_2_button=0x7f05000b;
        public static final int s2_1_button=0x7f05000c;
        public static final int s2_2_button=0x7f05000d;
        public static final int save_button=0x7f05000e;
        public static final int server_field=0x7f050001;
        public static final int server_label=0x7f050000;
        public static final int top_bar=0x7f050006;
        public static final int video_view=0x7f050003;
    }
    public static final class layout {
        public static final int srv1connect=0x7f030000;
        public static final int srv1console=0x7f030001;
        public static final int srv1settings=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int connect=0x7f040005;
        public static final int default_server=0x7f040002;
        public static final int revert=0x7f040007;
        public static final int save=0x7f040006;
        public static final int server_name=0x7f040000;
        public static final int srv1connect_name=0x7f040003;
        public static final int srv1settings_name=0x7f040004;
    }
}
